
# https://www.javadevjournal.com/spring-boot/shutdown-spring-boot-application/
management:
  endpoints:
    jmx.exposure.exclude:
    jmx.exposure.include: shutdown, info
    web.exposure.exclude:
    web.exposure.include:
  endpoint:
    shutdown:
      enabled: true

---
server:
  port: 8080

spring:
  profiles: dev

  cache:
    type: simple  # cache type 프로바이더를 찾을 수 없는 경우, ConcurrentHashMap 을 이용한다.

---
server:
  port: 8082

spring:
  profiles: test

  cache:
    type: none   # @EnableCache 가 적용되질 않음